name: e2e
on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run end to end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run pylint
        run: pylint "$GITHUB_WORKSPACE/base-provisioning-agent/*.py"
