name: e2e
on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run end to end tests
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: echo first step
      - name: Second step
        run: echo second step
