name: e2e
on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run end to end tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get install -y python3-venv
          cd "$GITHUB_WORKSPACE"
          python3 -m venv venv 
          . venv/bin/activate
          pip install pylint

      - name: Run pylint
        run: |
          cd "$GITHUB_WORKSPACE"
          . venv/bin/activate
          pylint "$GITHUB_WORKSPACE/base-provisioning-agent/report_ready.py"
